# Generated by Django 4.2 on 2025-06-19 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_alter_prompt_title_menu_prompt_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='prompts.menu'),
        ),
    ]
