# Generated by Django 4.2.10 on 2025-06-19 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_alter_prompt_title'),
        ('prompts', '0003_alter_prompt_menu'),
    ]

    operations = [
    ]
