# Generated by Django 4.2.10 on 2025-06-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_merge_0002_alter_prompt_title_0003_alter_prompt_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='output_format',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='role',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
