# Generated by Django 4.2.10 on 2025-06-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0005_prompt_example_prompt_goal_prompt_output_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='content',
            field=models.TextField(),
        ),
    ]
